# Generated by Django 5.2.4 on 2025-09-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='Registration',
            new_name='REGISTRATON',
        ),
    ]
