# Generated by Django 5.2.4 on 2025-09-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_registration_upload_registraton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='REGISTRATON',
            new_name='REGISTRATION',
        ),
    ]
