# Generated by Django 5.2.4 on 2025-09-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_registraton_upload_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
    ]
