# Generated by Django 5.2.4 on 2025-09-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_registration_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='district',
        ),
    ]
