# Generated by Django 5.2.6 on 2025-09-28 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_registration_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.upload')),
            ],
        ),
    ]
