# Generated by Django 5.2.6 on 2025-09-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_detection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detection',
        ),
    ]
