# Generated by Django 5.2.6 on 2025-09-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_detection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='upload',
            new_name='upload_file',
        ),
    ]
