# Generated by Django 5.2.6 on 2025-09-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_upload_detection_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='upload_file',
            new_name='upload_files',
        ),
    ]
