# Generated by Django 5.2.6 on 2025-09-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_upload_file_detection_upload_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='upload_files',
        ),
        migrations.AddField(
            model_name='detection',
            name='trash',
            field=models.CharField(default='', max_length=100),
        ),
    ]
