# Generated by Django 5.2.6 on 2025-09-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_detection_upload_files_detection_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='trash',
        ),
    ]
