# Generated by Django 5.2.6 on 2025-09-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_detection_trash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detection',
        ),
    ]
