# Generated by Django 5.2.6 on 2025-09-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
