# Generated by Django 5.2.6 on 2025-09-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_detection1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detection',
        ),
        migrations.DeleteModel(
            name='Detection1',
        ),
    ]
