# Generated by Django 5.2.6 on 2025-09-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_detection_delete_detection1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trash', models.CharField(max_length=400)),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.upload')),
            ],
        ),
    ]
